#pragma once

#include <aidl/vendor/brcm/helloworld/BnHelloWorld.h>

/**
 * @class HelloWorld
 * @brief Implementation of the HelloWorld AIDL interface.
 *
 * This class inherits from BnHelloWorld, which is the Binder-native (Bn) stub
 * generated by the AIDL tool for the HelloWorld interface. The Bn prefix indicates
 * that this class is intended to handle incoming IPC calls from clients.
 *
 * The HelloWorld class provides the actual logic for the service methods defined
 * in the AIDL specification. In particular, it implements the sayHello method,
 * which processes messages sent by clients.
 */
namespace aidl::vendor::brcm::helloworld {

class HelloWorld : public BnHelloWorld {
public:
    ndk::ScopedAStatus sayHello(const std::string& message) override;
};

}
